### ISSUE TITLE
Is v2 branch usable?

### ISSUE THREAD

**Issue by paolodina** [tserkov/vue-sse#18]
Hello, I need to integrate SSE with vue and found this project, very nice opportunity to use it.

Just to know, which branch should I use? I see a v2 updated recently but not sure if it's OK to use it right now (issue #12 is closed but #13 is not). Any opinion?

Thanks!

OT
Do you have any objection adding vue-sse to https://github.com/vuejs/awesome-vue? I can do the pull request if you like the idea.

**Comment by tserkov** [comment]
Hey there, @paolodina!

v2 is definitely usable and is highly recommended over v1. #13 is something I still need to implement, but will be added to v2 (likely in 2.2.0) and since I follow semantic versioning won't break the major version compatibility promise.

As for adding to awesome-vue, that sounds perfect, especially if you're willing to do the PR! 😄

**Comment by paolodina** [comment]
Well, thankyou very much! And for the PR, let's see what happens. https://github.com/vuejs/awesome-vue/pull/3695

Closing the ticket, cheers.
